name: Dart Code Metrics

on: [push]

jobs:
  check:
    name: dart-code-metrics-action

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "beta" # or: 'beta', 'dev', 'master' (or 'main')

      - name: dart-code-metrics
        uses: Flutterando/flutterando-metrics-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
